[versions]
project-name = "lifelog"
project-version-name = "0.0.1"
project-version-inc = "1"
android-sdk-compile = "35"
android-sdk-target = "34"
android-sdk-min = "24"
sqlite-wasm-year = "2024"
sqlite-wasm-version = "3460100"

kotlin = "2.1.0"
compose = "1.8.0-dev1905"
agp = "8.7.2"
vanniktech-publish = "0.29.0"
composekit = "a0928b5d"
kogit = "0.0.3-SNAPSHOT"
ktor = "3.0.1"
okio = "3.9.1"
sqldelight = "2.1.0-SNAPSHOT"
sqldelight-wasm = "f363703160" # TEMP SqlDelight
undercouch-download = "5.6.0"
image-loader = "1.9.0"
diff = "0.7.0"
uri-kmp = "0.0.18"

mokkery = "2.6.0-SNAPSHOT"
assertk = "0.28.1"

markdown = "0.7.3"
kotlinx-datetime = "0.6.0"
kotlinx-coroutines = "1.9.0"
kotlinx-serialization-json = "1.7.3"
androidx-activity-compose = "1.9.3"
navigation-common-ktx = "2.8.4"

[libraries]
composekit-util = { module = "dev.toastbits:composekit-util", version.ref = "composekit" }
composekit-context = { module = "dev.toastbits:composekit-context", version.ref = "composekit" }
composekit-settings = { module = "dev.toastbits:composekit-settings", version.ref = "composekit" }
composekit-theme = { module = "dev.toastbits:composekit-theme", version.ref = "composekit" }
composekit-navigation = { module = "dev.toastbits:composekit-navigation", version.ref = "composekit" }
composekit-components = { module = "dev.toastbits:composekit-components", version.ref = "composekit" }
composekit-commonsettings = { module = "dev.toastbits:composekit-commonsettings", version.ref = "composekit" }
composekit-application = { module = "dev.toastbits:composekit-application", version.ref = "composekit" }
kogit-core = { module = "dev.toastbits:kogit-core", version.ref = "kogit" }
kogit-memory = { module = "dev.toastbits:kogit-memory", version.ref = "kogit" }
kogit-system = { module = "dev.toastbits:kogit-system", version.ref = "kogit" }
image-loader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "image-loader" }
diff = { module = "io.github.petertrr:kotlin-multiplatform-diff", version.ref = "diff" }

kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
compose-plugin = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "compose" }
kotlin-compose-plugin = { module = "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin", version.ref = "kotlin" }
vanniktech-publish-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vanniktech-publish" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
markdown = { module = "org.jetbrains:markdown", version.ref = "markdown" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
sqldelight-extension-coroutines = { module = "com.github.toasterofbread.sqldelight:coroutines-extensions", version.ref = "sqldelight-wasm" }
sqldelight-driver-wasmjs = { module = "com.github.toasterofbread.sqldelight:web-worker-driver-wasm-js", version.ref = "sqldelight-wasm" }
sqldelight-driver-jvm = { module = "com.github.toasterofbread.sqldelight:sqlite-driver", version.ref = "sqldelight-wasm" }
sqldelight-driver-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
uri-kmp = { module = "com.eygraber:uri-kmp", version.ref = "uri-kmp" }

mokkery-plugin = { module = "dev.mokkery:dev.mokkery.gradle.plugin", version.ref = "mokkery" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
androidx-navigation-common-ktx = { group = "androidx.navigation", name = "navigation-common-ktx", version.ref = "navigation-common-ktx" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-publish" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight-wasm" }
undercouch-download = { id = "de.undercouch.download", version.ref = "undercouch-download" }
