package dev.toastbits.lifelog.application.settings.domain.group

import dev.toastbits.composekit.commonsettings.impl.group.ComposeKitSettingsGroupInterface

interface InterfacePreferencesGroup: ComposeKitSettingsGroupInterface
