package dev.toastbits.lifelog.application.settings.domain.group

import dev.toastbits.composekit.commonsettings.impl.group.ComposeKitInterfacePlatformSettingsGroup

interface InterfacePreferencesGroup: ComposeKitInterfacePlatformSettingsGroup
