name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container: archlinux
    
    steps:
      - name: test
        run: pacman --noconfirm -Syu mpv libappindicator-gtk3
