name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - run: wget https://nightly.link/toasterofbread/spmp-server/actions/runs/7282568410/spms-linux-debug.kexe.zip
    - run: unzip spms-linux-debug.kexe.zip

    - run: sudo apt install libmpv-dev libappindicator3-dev mpv

    - run: chmod +x ./spmp-server.kexe
    - run: ./spmp-server.kexe
