name: Mark issue with 'Waiting for response'

on:
  schedule:
    - cron: "0 0 * * *"
  issue_comment:
    types:
      - created
  workflow_dispatch:

jobs:
  issue-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: tiangolo/issue-manager@0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: '{"Waiting for response": {"delay": "P30DT0H0M0S", "message": "Closing, because it has been 30 days with no additional information."}}'
