name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: TeamGalacticraft/discord-reporter@1.0.0
        with:
          webhook: https://discord.com/api/webhooks/1210912462547845191/AU-lpdK9ui4PAZ_L3wdYvJ82JNmko7gpeivuMwP6t4jEGdTU2aXvDY3ewz1p0qOt5OTK
          token: ${{ secrets.GITHUB_TOKEN }}
