name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Archlinux
      run: curl -L https://github.com/zaoqi/github-actions-archlinux/raw/master/install.sh | sh
    - name: Docker hello-world
      run: |
        sudo pacman --noconfirm -Syu docker
        sudo systemctl start docker
        docker run --rm hello-world

    - name: test
      run: sudo pacman -Sy mpv libappindicator-gtk3
