name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:

      - uses: discord-actions/message@v2
        with:
          webhookUrl: https://discord.com/api/webhooks/1210912462547845191/AU-lpdK9ui4PAZ_L3wdYvJ82JNmko7gpeivuMwP6t4jEGdTU2aXvDY3ewz1p0qOt5OTK
          message: "[Build workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for commit [${{ github.event.head_commit.ref }}](${{ github.event.head_commit.url }}) (${{ github.event.head_commit.message }}) succeeded"
